"""pages/summarizer.py — מסכם חומר חכם + ייצוא PDF עם fpdf2 + pandas להיסטוריה"""
import streamlit as st
import pandas as pd
from datetime import datetime
from fpdf import FPDF # ספריית fpdf2 מיוצגת כאן כ-fpdf
from ai_utils import call_gemini, get_api_key
import io # מודול לטיפול בקלט/פלט בייטים בזיכרון

# הגדרות נושאים קבועים בעברית ובאנגלית
SUBJECTS_HE = ["כללי","מתמטיקה","אנגלית","עברית","פיזיקה","כימיה",
                "ביולוגיה","היסטוריה","ספרות",'תנ"ך',"מדעי המחשב"]
SUBJECTS_EN = ["General","Math","English","Hebrew","Physics","Chemistry",
                "Biology","History","Literature","Bible","CS"]


# ── יצירת דוח PDF (באמצעות fpdf2) ────────────────────────────────────────────
def _make_pdf(subject: str, style: str, summary: str, original_len: int, lang: str) -> bytes:
    """
    יוצר קובץ PDF עם הסיכום שנוצר על ידי ה-AI.
    :param subject: נושא הסיכום.
    :param style: סגנון הסיכום (למשל, נקודות מרכזיות, סיפורי).
    :param summary: טקסט הסיכום שנוצר.
    :param original_len: אורך הטקסט המקורי בתווים.
    :param lang: שפת הממשק (he/en).
    :return: קובץ PDF בפורמט בייטים.
    """
    pdf = FPDF()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=15)

    # שימוש בגופן מובנה (אין תמיכה מובנית בעברית ב-fpdf2 ללא הטמעת פונטים)
    # עבור תוכן בעברית, פרטי המטא-דאטה מתורגמים/מוצגים בלטינית, והסיכום נכתב כפי שהוא.
    pdf.set_font("Helvetica", "B", 20)
    pdf.set_text_color(110, 231, 183) # צבע ירוק-טורקיז לכותרות
    pdf.cell(0, 12, "Gradeup — Smart Summarizer", ln=True, align="C")

    pdf.set_font("Helvetica", "", 11)
    pdf.set_text_color(180, 190, 210) # צבע אפור בהיר לפרטים
    pdf.cell(0, 8, f"Subject: {subject}  |  Style: {style}  |  {datetime.now().strftime('%d/%m/%Y %H:%M')}", ln=True, align="C")
    pdf.cell(0, 6, f"Original: {original_len} chars  |  Generated by Gradeup AI", ln=True, align="C")

    pdf.ln(6)
    pdf.set_draw_color(30, 42, 61) # צבע קו הפרדה
    pdf.line(10, pdf.get_y(), 200, pdf.get_y()) # קו הפרדה ויזואלי
    pdf.ln(6)

    pdf.set_font("Helvetica", "", 11)
    pdf.set_text_color(230, 235, 245) # צבע לבן-אפור לטקסט הסיכום

    # כתיבת הסיכום שורה אחר שורה, עם טיפול מיוחד לכותרות וקווים ארוכים
    for line in summary.split("\n"):
        line = line.strip()
        if not line: # אם שורה ריקה, הוסף רווח קטן
            pdf.ln(4)
            continue
        # אם השורה מתחילה בסימני כותרת (Markdown), עצב אותה ככותרת
        if line.startswith("**") or line.startswith("##") or line.startswith("*"):
            pdf.set_font("Helvetica", "B", 12)
            pdf.set_text_color(110, 231, 183) # צבע ירוק-טורקיז לכותרות פנימיות
            clean = line.lstrip("#* ") # הסר את סימני המארקדאון
            pdf.multi_cell(0, 7, clean) # כתוב את הכותרת
            pdf.set_font("Helvetica", "", 11) # חזור לגופן רגיל
            pdf.set_text_color(230, 235, 245) # חזור לצבע טקסט רגיל
        else:
            pdf.multi_cell(0, 6, line) # כתוב שורה רגילה

    pdf.ln(8)
    pdf.set_font("Helvetica", "I", 9)
    pdf.set_text_color(60, 80, 100) # צבע אפור כהה לפוטר
    pdf.cell(0, 6, "gradeup.co.il", ln=True, align="C")

    return bytes(pdf.output()) # החזרת הדוח כבייטים


# ── פונקציית רינדור ראשית ────────────────────────────────────────────
def render(t):
    """
    פונקציית הרינדור הראשית של עמוד המסכם החכם.
    מאתחלת את היסטוריית הסיכומים, בודקת מפתח API ויוצרת לשוניות.
    :param t: פונקציית תרגום (למשל, מתרגם מחרוזות).
    """
    lang = st.session_state.lang
    # כותרת ראשית של העמוד
    st.markdown(f'<div class="sf-section-title">{t("sum_title")}</div>', unsafe_allow_html=True)

    # אתחול היסטוריית הסיכומים ב-session state אם אינה קיימת
    if "sum_history" not in st.session_state:
        st.session_state.sum_history = []  # רשימת מילונים שבהמשך תשמש ל-pandas

    # בדיקה אם מפתח ה-API זמין, אחרת הצג אזהרה וצא
    if not get_api_key():
        st.warning(t("hw_api_missing"))
        return

    # יצירת לשוניות לניווט בין מסכם הטקסט להיסטוריית הסיכומים
    tab_text, tab_hist = st.tabs([
        t("sum_tab_text"),
        t("sum_tab_history"),
    ])

    # הצגת התוכן של כל לשונית באמצעות פונקציות עזר
    with tab_text:
        _render_text(t, lang)
    with tab_hist:
        _render_history(t, lang)


# ── לשונית מסכם טקסט ───────────────────────────────────────────────────────
def _render_text(t, lang):
    """
    מרנדר את לשונית "מסכם טקסט" המאפשרת למשתמש להדביק טקסט ולקבל סיכום AI.
    :param t: פונקציית תרגום.
    :param lang: שפת הממשק.
    """
    subjects = SUBJECTS_HE if lang == "he" else SUBJECTS_EN
    styles_he = ["נקודות מרכזיות","סיפורי (קריא)","שאלות מבחן","מושגי מפתח"]
    styles_en = ["Key bullets","Narrative","Exam questions","Key terms"]
    styles    = styles_he if lang == "he" else styles_en

    # שדות קלט לבחירת נושא וסגנון סיכום
    c1, c2 = st.columns(2)
    with c1:
        subj  = st.selectbox(t("sum_subject"), subjects, key="sum_subj")
    with c2:
        style = st.selectbox(t("sum_style"),  styles,   key="sum_style_sel")

    # שדה קלט להדבקת הטקסט לסיכום
    text = st.text_area(
        t("sum_paste_label"),
        height=220,
        placeholder=(
            "הדבק כאן טקסט מספר לימוד, הרצאה, מאמר…\n\n"
            "לדוגמה: 'הפוטוסינתזה היא תהליך שבו צמחים ממירים אור שמש, מים ופחמן דו-חמצני לגלוקוז וחמצן…'"
            if lang == "he" else
            "Paste textbook text, lecture notes, article…\n\n"
            "E.g.: 'Photosynthesis is the process by which plants convert sunlight, water and CO2 into glucose and oxygen…'"
        ),
        key="sum_text_input"
    )

    # הצגת מונה תווים ומילים
    char_count = len(text)
    word_count = len(text.split()) if text else 0
    st.markdown(
        f'<div style="color:var(--muted);font-size:.8rem;text-align:left">'
        f'{char_count} {t("sum_chars")} · {word_count} {"מילים" if lang=="he" else "words"}</div>',
        unsafe_allow_html=True,
    )

    # אתחול משתנה לתוצאת הסיכום ב-session state
    if "sum_result" not in st.session_state:
        st.session_state.sum_result = None

    # כפתורים לביצוע סיכום ולניקוי
    col_go, col_clear = st.columns([3, 1])
    with col_go:
        go_btn = st.button(t("sum_go"), type="primary", use_container_width=True, key="sum_go_btn")
    with col_clear:
        if st.button(t("clear"), key="sum_clear_btn", use_container_width=True):
            st.session_state.sum_result = None # איפוס תוצאת הסיכום
            st.rerun() # רענון העמוד

    if go_btn:
        if char_count < 50: # בדיקה שאורך הטקסט מספיק לסיכום
            st.error("הטקסט קצר מדי — הדבק לפחות 50 תווים" if lang=="he" else "Text too short — paste at least 50 chars")
        else:
            # מיפוי סגנונות הסיכום להנחיות מערכת עבור ה-AI
            sys_map = {
                "נקודות מרכזיות": "סכם ב-5-8 נקודות מרכזיות עם כותרת לכל נקודה.",
                "Key bullets":     "Summarize in 5-8 key bullet points with a title for each.",
                "סיפורי (קריא)":  "כתוב סיכום קריא ורציף בפסקאות, כמו הסבר לחבר.",
                "Narrative":       "Write a readable, flowing summary in paragraphs, like explaining to a friend.",
                "שאלות מבחן":     "צור 6-8 שאלות מבחן (עם תשובות) מהחומר.",
                "Exam questions":  "Create 6-8 exam questions (with answers) from the material.",
                "מושגי מפתח":     "חלץ את 8-12 מושגי המפתח עם הגדרה קצרה לכל אחד.",
                "Key terms":       "Extract 8-12 key terms with a short definition for each.",
            }
            # בניית הנחיית המערכת המלאה ל-AI
            sys = (
                f"אתה מסכם חומר לימודי לתלמיד תיכון. מקצוע: {subj}. "
                f"סגנון: {sys_map.get(style, style)} " # שימוש בהנחיה מותאמת לסגנון
                "השתמש בעברית. היה מדויק ותמציתי."
                if lang == "he" else
                f"You summarize study material for a high school student. Subject: {subj}. "
                f"Style: {sys_map.get(style, style)} "
                "Be accurate and concise."
            )
            with st.spinner("📝 " + ("מסכם…" if lang=="he" else "Summarizing…")): # הצגת אנימציית טעינה
                try:
                    # קריאה לפונקציית ה-AI ליצירת הסיכום
                    result = call_gemini(
                        system_prompt=sys,
                        user_text=text,
                        max_tokens=1500, # הגבלת אורך התשובה
                        temperature=0.5, # רמת יצירתיות
                    )
                    st.session_state.sum_result = result # שמירת הסיכום ב-session state
                    # שמירת הסיכום בהיסטוריה (מילון מוכן ל-pandas)
                    st.session_state.sum_history.append({
                        "date":    datetime.now().strftime("%d/%m/%Y %H:%M"),
                        "subject": subj,
                        "style":   style,
                        "chars":   char_count,
                        "words":   word_count,
                        "summary": result,
                        "original": text, # שמירת הטקסט המקורי גם כן
                    })
                except Exception as e:
                    st.error(str(e)) # הצגת הודעת שגיאה אם קריאת ה-AI נכשלה

    # הצגת תוצאת הסיכום
    if st.session_state.sum_result:
        st.markdown(
            f'<div class="sf-bubble-ai" style="margin-top:1rem">'
            f'<div class="sf-bubble-label">{t("ai_label")} — {subj} / {style}</div>'
            f'{st.session_state.sum_result}</div>',
            unsafe_allow_html=True,
        )
        # כפתור לייצוא הסיכום ל-PDF
        if st.button(f"📥 {t('sum_export_pdf')}", key="sum_pdf_btn", type="primary"):
            with st.spinner("PDF…"):
                try:
                    # יצירת קובץ PDF באמצעות הפונקציה _make_pdf
                    pdf_bytes = _make_pdf(subj, style, st.session_state.sum_result, char_count, lang)
                    st.download_button(
                        label="📥 " + ("הורד PDF" if lang=="he" else "Download PDF"),
                        data=pdf_bytes,
                        file_name=f"gradeup_summary_{subj}_{datetime.now().strftime('%Y%m%d')}.pdf",
                        mime="application/pdf",
                        key="sum_pdf_dl",
                    )
                except Exception as e:
                    st.error(str(e)) # הצגת שגיאה אם יצירת PDF נכשלה


# ── לשונית היסטוריית סיכומים (באמצעות pandas) ────────────────────────────────
def _render_history(t, lang):
    """
    מרנדר את לשונית "היסטוריה" המציגה את כל הסיכומים שנוצרו בעבר.
    :param t: פונקציית תרגום.
    :param lang: שפת הממשק.
    """
    history = st.session_state.sum_history
    if not history: # אם אין סיכומים בהיסטוריה, הצג הודעה
        st.info(t("sum_no_history"))
        return

    # בניית DataFrame של pandas מהיסטוריית הסיכומים
    df = pd.DataFrame(history)[["date","subject","style","chars","words"]]
    # שינוי שמות העמודות בהתאם לשפה
    df.columns = (
        ["תאריך","מקצוע","סגנון","תווים","מילים"]
        if lang == "he" else
        ["Date","Subject","Style","Chars","Words"]
    )

    # כותרת לשונית ההיסטוריה, כולל מספר הסיכומים
    st.markdown(
        f'<div class="sf-section-title">{"סיכומים שמורים — " if lang=="he" else "Saved summaries — "}'
        f'{len(history)}</div>',
        unsafe_allow_html=True,
    )

    # הצגת שורת סטטיסטיקות סיכום (באמצעות pandas)
    total_chars = pd.Series([h["chars"] for h in history]).sum() # סך כל התווים שסוכמו
    avg_words   = pd.Series([h["words"] for h in history]).mean() # ממוצע מילים לסיכום
    top_subject = pd.Series([h["subject"] for h in history]).mode()[0] # הנושא הנפוץ ביותר

    c1, c2, c3 = st.columns(3)
    with c1:
        st.markdown(
            f'<div class="sf-stat"><div class="sf-stat-num">{len(history)}</div>'
            f'<div class="sf-stat-label">{"סיכומים" if lang=="he" else "Summaries"}</div></div>',
            unsafe_allow_html=True,
        )
    with c2:
        st.markdown(
            f'<div class="sf-stat"><div class="sf-stat-num">{int(avg_words)}</div>'
            f'<div class="sf-stat-label">{"ממוצע מילים" if lang=="he" else "Avg words"}</div></div>',
            unsafe_allow_html=True,
        )
    with c3:
        st.markdown(
            f'<div class="sf-stat"><div class="sf-stat-num" style="font-size:1rem">{top_subject}</div>'
            f'<div class="sf-stat-label">{"מקצוע מוביל" if lang=="he" else "Top subject"}</div></div>',
            unsafe_allow_html=True,
        )

    # הצגת ה-DataFrame ב-Streamlit
    st.dataframe(df, use_container_width=True, hide_index=True)

    # כפתור לייצוא היסטוריית הסיכומים כקובץ CSV
    buf = io.BytesIO() # יצירת חיץ בזיכרון
    # df.to_excel(buf, index=False, engine="openpyxl") # יצוא לאקסל (דורש openpyxl)
    # יצוא ל-CSV כ-fallback או כברירת מחדל
    csv_bytes = df.to_csv(index=False).encode("utf-8-sig") # קידוד לטיפול נכון בעברית
    st.download_button(
        "📥 " + ("ייצא CSV" if lang=="he" else "Export CSV"),
        data=csv_bytes,
        file_name="gradeup_summaries.csv",
        mime="text/csv",
        key="sum_hist_export",
    )

    # הצגת כל סיכום בנפרד בתוך expander
    st.markdown("---") # קו הפרדה
    for i, entry in enumerate(reversed(history)): # הצגה בסדר הפוך (החדש ביותר ראשון)
        with st.expander(f"📝 {entry['subject']} — {entry['date']} ({entry['style']})"):
            st.markdown(
                f'<div style="font-size:.88rem;color:var(--muted)">{entry["summary"]}</div>',
                unsafe_allow_html=True,
            )
            # כפתור לייצוא כל סיכום ספציפי ל-PDF
            if st.button("📥 PDF", key=f"hist_pdf_{i}"):
                pdf_b = _make_pdf(entry["subject"], entry["style"],
                                   entry["summary"], entry["chars"], lang)
                st.download_button("⬇️", pdf_b,
                    f"gradeup_{entry['subject']}_{i}.pdf", "application/pdf",
                    key=f"hist_dl_{i}")
