"""pages/summarizer.py — מסכם חומר חכם + ייצוא PDF עם fpdf2 + pandas להיסטוריה"""
import streamlit as st
import pandas as pd
from datetime import datetime
from fpdf import FPDF
from ai_utils import call_gemini, get_api_key
import io

SUBJECTS_HE = ["כללי","מתמטיקה","אנגלית","עברית","פיזיקה","כימיה",
                "ביולוגיה","היסטוריה","ספרות",'תנ"ך',"מדעי המחשב"]
SUBJECTS_EN = ["General","Math","English","Hebrew","Physics","Chemistry",
                "Biology","History","Literature","Bible","CS"]


# ── PDF export (fpdf2) ────────────────────────────────────────────────────
def _make_pdf(subject: str, style: str, summary: str, original_len: int, lang: str) -> bytes:
    pdf = FPDF()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=15)

    # Use built-in font (no Hebrew support in fpdf2 without TTF)
    # For Hebrew content we transliterate the metadata and keep summary as-is
    pdf.set_font("Helvetica", "B", 20)
    pdf.set_text_color(110, 231, 183)
    pdf.cell(0, 12, "Gradeup — Smart Summarizer", ln=True, align="C")

    pdf.set_font("Helvetica", "", 11)
    pdf.set_text_color(180, 190, 210)
    pdf.cell(0, 8, f"Subject: {subject}  |  Style: {style}  |  {datetime.now().strftime('%d/%m/%Y %H:%M')}", ln=True, align="C")
    pdf.cell(0, 6, f"Original: {original_len} chars  |  Generated by Gradeup AI", ln=True, align="C")

    pdf.ln(6)
    pdf.set_draw_color(30, 42, 61)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(6)

    pdf.set_font("Helvetica", "", 11)
    pdf.set_text_color(230, 235, 245)

    # Write summary line by line (handle long lines)
    for line in summary.split("\n"):
        line = line.strip()
        if not line:
            pdf.ln(4)
            continue
        if line.startswith("**") or line.startswith("##") or line.startswith("*"):
            pdf.set_font("Helvetica", "B", 12)
            pdf.set_text_color(110, 231, 183)
            clean = line.lstrip("#* ")
            pdf.multi_cell(0, 7, clean)
            pdf.set_font("Helvetica", "", 11)
            pdf.set_text_color(230, 235, 245)
        else:
            pdf.multi_cell(0, 6, line)

    pdf.ln(8)
    pdf.set_font("Helvetica", "I", 9)
    pdf.set_text_color(60, 80, 100)
    pdf.cell(0, 6, "gradeup.co.il", ln=True, align="C")

    return bytes(pdf.output())


# ── Main render ───────────────────────────────────────────────────────────
def render(t):
    lang = st.session_state.lang
    st.markdown(f'<div class="sf-section-title">{t("sum_title")}</div>', unsafe_allow_html=True)

    if "sum_history" not in st.session_state:
        st.session_state.sum_history = []  # list of dicts → pandas later

    if not get_api_key():
        st.warning(t("hw_api_missing"))
        return

    tab_text, tab_hist = st.tabs([
        t("sum_tab_text"),
        t("sum_tab_history"),
    ])

    with tab_text:
        _render_text(t, lang)
    with tab_hist:
        _render_history(t, lang)


def _render_text(t, lang):
    subjects = SUBJECTS_HE if lang == "he" else SUBJECTS_EN
    styles_he = ["נקודות מרכזיות","סיפורי (קריא)","שאלות מבחן","מושגי מפתח"]
    styles_en = ["Key bullets","Narrative","Exam questions","Key terms"]
    styles    = styles_he if lang == "he" else styles_en

    c1, c2 = st.columns(2)
    with c1:
        subj  = st.selectbox(t("sum_subject"), subjects, key="sum_subj")
    with c2:
        style = st.selectbox(t("sum_style"),  styles,   key="sum_style_sel")

    text = st.text_area(
        t("sum_paste_label"),
        height=220,
        placeholder=(
            "הדבק כאן טקסט מספר לימוד, הרצאה, מאמר…\n\n"
            "לדוגמה: 'הפוטוסינתזה היא תהליך שבו צמחים ממירים אור שמש, מים ופחמן דו-חמצני לגלוקוז וחמצן…'"
            if lang == "he" else
            "Paste textbook text, lecture notes, article…\n\n"
            "E.g.: 'Photosynthesis is the process by which plants convert sunlight, water and CO2 into glucose and oxygen…'"
        ),
        key="sum_text_input"
    )

    char_count = len(text)
    word_count = len(text.split()) if text else 0
    st.markdown(
        f'<div style="color:var(--muted);font-size:.8rem;text-align:left">'
        f'{char_count} {t("sum_chars")} · {word_count} {"מילים" if lang=="he" else "words"}</div>',
        unsafe_allow_html=True,
    )

    if "sum_result" not in st.session_state:
        st.session_state.sum_result = None

    col_go, col_clear = st.columns([3, 1])
    with col_go:
        go_btn = st.button(t("sum_go"), type="primary", use_container_width=True, key="sum_go_btn")
    with col_clear:
        if st.button(t("clear"), key="sum_clear_btn", use_container_width=True):
            st.session_state.sum_result = None
            st.rerun()

    if go_btn:
        if char_count < 50:
            st.error("הטקסט קצר מדי — הדבק לפחות 50 תווים" if lang=="he" else "Text too short — paste at least 50 chars")
        else:
            sys_map = {
                "נקודות מרכזיות": "סכם ב-5-8 נקודות מרכזיות עם כותרת לכל נקודה.",
                "Key bullets":     "Summarize in 5-8 key bullet points with a title for each.",
                "סיפורי (קריא)":  "כתוב סיכום קריא ורציף בפסקאות, כמו הסבר לחבר.",
                "Narrative":       "Write a readable, flowing summary in paragraphs, like explaining to a friend.",
                "שאלות מבחן":     "צור 6-8 שאלות מבחן (עם תשובות) מהחומר.",
                "Exam questions":  "Create 6-8 exam questions (with answers) from the material.",
                "מושגי מפתח":     "חלץ את 8-12 מושגי המפתח עם הגדרה קצרה לכל אחד.",
                "Key terms":       "Extract 8-12 key terms with a short definition for each.",
            }
            sys = (
                f"אתה מסכם חומר לימודי לתלמיד תיכון. מקצוע: {subj}. "
                f"סגנון: {sys_map.get(style, style)} "
                "השתמש בעברית. היה מדויק ותמציתי."
                if lang == "he" else
                f"You summarize study material for a high school student. Subject: {subj}. "
                f"Style: {sys_map.get(style, style)} "
                "Be accurate and concise."
            )
            with st.spinner("📝 " + ("מסכם…" if lang=="he" else "Summarizing…")):
                try:
                    result = call_gemini(
                        system_prompt=sys,
                        user_text=text,
                        max_tokens=1500,
                        temperature=0.5,
                    )
                    st.session_state.sum_result = result
                    # Save to history (pandas-ready dict)
                    st.session_state.sum_history.append({
                        "date":    datetime.now().strftime("%d/%m/%Y %H:%M"),
                        "subject": subj,
                        "style":   style,
                        "chars":   char_count,
                        "words":   word_count,
                        "summary": result,
                        "original": text,
                    })
                except Exception as e:
                    st.error(str(e))

    # Display result
    if st.session_state.sum_result:
        st.markdown(
            f'<div class="sf-bubble-ai" style="margin-top:1rem">'
            f'<div class="sf-bubble-label">{t("ai_label")} — {subj} / {style}</div>'
            f'{st.session_state.sum_result}</div>',
            unsafe_allow_html=True,
        )
        # PDF export (fpdf2)
        if st.button(f"📥 {t('sum_export_pdf')}", key="sum_pdf_btn", type="primary"):
            with st.spinner("PDF…"):
                try:
                    pdf_bytes = _make_pdf(subj, style, st.session_state.sum_result, char_count, lang)
                    st.download_button(
                        label="📥 " + ("הורד PDF" if lang=="he" else "Download PDF"),
                        data=pdf_bytes,
                        file_name=f"gradeup_summary_{subj}_{datetime.now().strftime('%Y%m%d')}.pdf",
                        mime="application/pdf",
                        key="sum_pdf_dl",
                    )
                except Exception as e:
                    st.error(str(e))


# ── History (pandas) ──────────────────────────────────────────────────────
def _render_history(t, lang):
    history = st.session_state.sum_history
    if not history:
        st.info(t("sum_no_history"))
        return

    # Build pandas DataFrame
    df = pd.DataFrame(history)[["date","subject","style","chars","words"]]
    df.columns = (
        ["תאריך","מקצוע","סגנון","תווים","מילים"]
        if lang == "he" else
        ["Date","Subject","Style","Chars","Words"]
    )

    st.markdown(
        f'<div class="sf-section-title">{"סיכומים שמורים — " if lang=="he" else "Saved summaries — "}'
        f'{len(history)}</div>',
        unsafe_allow_html=True,
    )

    # Stats row (pandas)
    total_chars = pd.Series([h["chars"] for h in history]).sum()
    avg_words   = pd.Series([h["words"] for h in history]).mean()
    top_subject = pd.Series([h["subject"] for h in history]).mode()[0]

    c1, c2, c3 = st.columns(3)
    with c1:
        st.markdown(
            f'<div class="sf-stat"><div class="sf-stat-num">{len(history)}</div>'
            f'<div class="sf-stat-label">{"סיכומים" if lang=="he" else "Summaries"}</div></div>',
            unsafe_allow_html=True,
        )
    with c2:
        st.markdown(
            f'<div class="sf-stat"><div class="sf-stat-num">{int(avg_words)}</div>'
            f'<div class="sf-stat-label">{"ממוצע מילים" if lang=="he" else "Avg words"}</div></div>',
            unsafe_allow_html=True,
        )
    with c3:
        st.markdown(
            f'<div class="sf-stat"><div class="sf-stat-num" style="font-size:1rem">{top_subject}</div>'
            f'<div class="sf-stat-label">{"מקצוע מוביל" if lang=="he" else "Top subject"}</div></div>',
            unsafe_allow_html=True,
        )

    # DataFrame display
    st.dataframe(df, use_container_width=True, hide_index=True)

    # Export history as Excel (pandas)
    buf = io.BytesIO()
    df.to_excel(buf, index=False, engine="openpyxl") if True else df.to_csv(buf, index=False)
    # fallback: CSV
    csv_bytes = df.to_csv(index=False).encode("utf-8-sig")
    st.download_button(
        "📥 " + ("ייצא CSV" if lang=="he" else "Export CSV"),
        data=csv_bytes,
        file_name="gradeup_summaries.csv",
        mime="text/csv",
        key="sum_hist_export",
    )

    # Expand each summary
    st.markdown("---")
    for i, entry in enumerate(reversed(history)):
        with st.expander(f"📝 {entry['subject']} — {entry['date']} ({entry['style']})"):
            st.markdown(
                f'<div style="font-size:.88rem;color:var(--muted)">{entry["summary"]}</div>',
                unsafe_allow_html=True,
            )
            # Re-export PDF per summary
            if st.button("📥 PDF", key=f"hist_pdf_{i}"):
                pdf_b = _make_pdf(entry["subject"], entry["style"],
                                   entry["summary"], entry["chars"], lang)
                st.download_button("⬇️", pdf_b,
                    f"gradeup_{entry['subject']}_{i}.pdf", "application/pdf",
                    key=f"hist_dl_{i}")